# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: DockerPublish

on:
  release:
    types: [created]
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**/*'
      - '.github/**/*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**/*'
      - '.github/**/*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.302+8
        distribution: 'temurin'
        server-id: javafamily-central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Install parent
      run: mvn clean install -N
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTER_USER_NAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTER_PASSWORD }}

    - name: Compile and publish to docker hub
      run: mvn clean verify
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_CENTER_USER_NAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTER_PASSWORD }}
